[package]
name = "wormhole-solana-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.16"
solana-sdk = "1.16"
solana-transaction-status = "1.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tokio = { version = "1.28", features = ["full"] }
clap = { version = "4.3", features = ["derive"] }
base64 = "0.21"
borsh = "0.10"
bs58 = "0.5"
wormhole-sdk = "0.1" # Wormhole SDK for Rust

[lib]
name = "wormhole_solana_monitor"
path = "src/lib.rs"

[[bin]]
name = "wormhole-solana-cli"
path = "src/main.rs"